controllers/ReportController.php
<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 01.05.18
 * Time: 16:21
 */

namespace app\controllers;


use app\models\ReportService;
use app\models\UploadForm;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class ReportController extends Controller
{
    public function actionUpload()
    {
        $uploadForm = new UploadForm();

        $profiPoints = [];
        if (Yii::$app->request->isPost) {
            $uploadForm->reportFile = UploadedFile::getInstance($uploadForm, 'reportFile');
            if ($uploadForm->upload()) {

                try {
                    $reportService = new ReportService();
                    $reportService->parseFile($uploadForm->getFilePath());
                    $profiPoints = $reportService->getProfitPoints();
                } catch (\Exception $e) {
                    Yii::error($e->getMessage());
                }

                if (!$profiPoints) {
                    $uploadForm->addError('reportFile', "Файл с неправильной структурой");
                }
            }
        }

        return $this->render('upload', [
            'uploadForm' => $uploadForm,
            'points'     => $profiPoints,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/report/upload']],
            ['label' => 'О приложении', 'url' => ['/site/about']],
            ['label' => 'Контакты', 'url' => ['/site/contact']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>